/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as WireUpdateWireImport } from './routes/wire/update-wire'
import { Route as WireListWireImport } from './routes/wire/list-wire'
import { Route as WireDeleteWireImport } from './routes/wire/delete-wire'
import { Route as WireCreateWireImport } from './routes/wire/create-wire'
import { Route as OrderUpdateOrderImport } from './routes/order/update-order'
import { Route as OrderListOrderImport } from './routes/order/list-order'
import { Route as OrderDeleteOrderImport } from './routes/order/delete-order'
import { Route as OrderCreateOrdersImport } from './routes/order/create-orders'
import { Route as CoilUpdateCoilImport } from './routes/coil/update-coil'
import { Route as CoilListCoilImport } from './routes/coil/list-coil'
import { Route as CoilDeleteCoilImport } from './routes/coil/delete-coil'
import { Route as CoilCreateCoilImport } from './routes/coil/create-coil'

// Create/Update Routes

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const WireUpdateWireRoute = WireUpdateWireImport.update({
  id: '/wire/update-wire',
  path: '/wire/update-wire',
  getParentRoute: () => rootRoute,
} as any)

const WireListWireRoute = WireListWireImport.update({
  id: '/wire/list-wire',
  path: '/wire/list-wire',
  getParentRoute: () => rootRoute,
} as any)

const WireDeleteWireRoute = WireDeleteWireImport.update({
  id: '/wire/delete-wire',
  path: '/wire/delete-wire',
  getParentRoute: () => rootRoute,
} as any)

const WireCreateWireRoute = WireCreateWireImport.update({
  id: '/wire/create-wire',
  path: '/wire/create-wire',
  getParentRoute: () => rootRoute,
} as any)

const OrderUpdateOrderRoute = OrderUpdateOrderImport.update({
  id: '/order/update-order',
  path: '/order/update-order',
  getParentRoute: () => rootRoute,
} as any)

const OrderListOrderRoute = OrderListOrderImport.update({
  id: '/order/list-order',
  path: '/order/list-order',
  getParentRoute: () => rootRoute,
} as any)

const OrderDeleteOrderRoute = OrderDeleteOrderImport.update({
  id: '/order/delete-order',
  path: '/order/delete-order',
  getParentRoute: () => rootRoute,
} as any)

const OrderCreateOrdersRoute = OrderCreateOrdersImport.update({
  id: '/order/create-orders',
  path: '/order/create-orders',
  getParentRoute: () => rootRoute,
} as any)

const CoilUpdateCoilRoute = CoilUpdateCoilImport.update({
  id: '/coil/update-coil',
  path: '/coil/update-coil',
  getParentRoute: () => rootRoute,
} as any)

const CoilListCoilRoute = CoilListCoilImport.update({
  id: '/coil/list-coil',
  path: '/coil/list-coil',
  getParentRoute: () => rootRoute,
} as any)

const CoilDeleteCoilRoute = CoilDeleteCoilImport.update({
  id: '/coil/delete-coil',
  path: '/coil/delete-coil',
  getParentRoute: () => rootRoute,
} as any)

const CoilCreateCoilRoute = CoilCreateCoilImport.update({
  id: '/coil/create-coil',
  path: '/coil/create-coil',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/coil/create-coil': {
      id: '/coil/create-coil'
      path: '/coil/create-coil'
      fullPath: '/coil/create-coil'
      preLoaderRoute: typeof CoilCreateCoilImport
      parentRoute: typeof rootRoute
    }
    '/coil/delete-coil': {
      id: '/coil/delete-coil'
      path: '/coil/delete-coil'
      fullPath: '/coil/delete-coil'
      preLoaderRoute: typeof CoilDeleteCoilImport
      parentRoute: typeof rootRoute
    }
    '/coil/list-coil': {
      id: '/coil/list-coil'
      path: '/coil/list-coil'
      fullPath: '/coil/list-coil'
      preLoaderRoute: typeof CoilListCoilImport
      parentRoute: typeof rootRoute
    }
    '/coil/update-coil': {
      id: '/coil/update-coil'
      path: '/coil/update-coil'
      fullPath: '/coil/update-coil'
      preLoaderRoute: typeof CoilUpdateCoilImport
      parentRoute: typeof rootRoute
    }
    '/order/create-orders': {
      id: '/order/create-orders'
      path: '/order/create-orders'
      fullPath: '/order/create-orders'
      preLoaderRoute: typeof OrderCreateOrdersImport
      parentRoute: typeof rootRoute
    }
    '/order/delete-order': {
      id: '/order/delete-order'
      path: '/order/delete-order'
      fullPath: '/order/delete-order'
      preLoaderRoute: typeof OrderDeleteOrderImport
      parentRoute: typeof rootRoute
    }
    '/order/list-order': {
      id: '/order/list-order'
      path: '/order/list-order'
      fullPath: '/order/list-order'
      preLoaderRoute: typeof OrderListOrderImport
      parentRoute: typeof rootRoute
    }
    '/order/update-order': {
      id: '/order/update-order'
      path: '/order/update-order'
      fullPath: '/order/update-order'
      preLoaderRoute: typeof OrderUpdateOrderImport
      parentRoute: typeof rootRoute
    }
    '/wire/create-wire': {
      id: '/wire/create-wire'
      path: '/wire/create-wire'
      fullPath: '/wire/create-wire'
      preLoaderRoute: typeof WireCreateWireImport
      parentRoute: typeof rootRoute
    }
    '/wire/delete-wire': {
      id: '/wire/delete-wire'
      path: '/wire/delete-wire'
      fullPath: '/wire/delete-wire'
      preLoaderRoute: typeof WireDeleteWireImport
      parentRoute: typeof rootRoute
    }
    '/wire/list-wire': {
      id: '/wire/list-wire'
      path: '/wire/list-wire'
      fullPath: '/wire/list-wire'
      preLoaderRoute: typeof WireListWireImport
      parentRoute: typeof rootRoute
    }
    '/wire/update-wire': {
      id: '/wire/update-wire'
      path: '/wire/update-wire'
      fullPath: '/wire/update-wire'
      preLoaderRoute: typeof WireUpdateWireImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coil/create-coil': typeof CoilCreateCoilRoute
  '/coil/delete-coil': typeof CoilDeleteCoilRoute
  '/coil/list-coil': typeof CoilListCoilRoute
  '/coil/update-coil': typeof CoilUpdateCoilRoute
  '/order/create-orders': typeof OrderCreateOrdersRoute
  '/order/delete-order': typeof OrderDeleteOrderRoute
  '/order/list-order': typeof OrderListOrderRoute
  '/order/update-order': typeof OrderUpdateOrderRoute
  '/wire/create-wire': typeof WireCreateWireRoute
  '/wire/delete-wire': typeof WireDeleteWireRoute
  '/wire/list-wire': typeof WireListWireRoute
  '/wire/update-wire': typeof WireUpdateWireRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coil/create-coil': typeof CoilCreateCoilRoute
  '/coil/delete-coil': typeof CoilDeleteCoilRoute
  '/coil/list-coil': typeof CoilListCoilRoute
  '/coil/update-coil': typeof CoilUpdateCoilRoute
  '/order/create-orders': typeof OrderCreateOrdersRoute
  '/order/delete-order': typeof OrderDeleteOrderRoute
  '/order/list-order': typeof OrderListOrderRoute
  '/order/update-order': typeof OrderUpdateOrderRoute
  '/wire/create-wire': typeof WireCreateWireRoute
  '/wire/delete-wire': typeof WireDeleteWireRoute
  '/wire/list-wire': typeof WireListWireRoute
  '/wire/update-wire': typeof WireUpdateWireRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/coil/create-coil': typeof CoilCreateCoilRoute
  '/coil/delete-coil': typeof CoilDeleteCoilRoute
  '/coil/list-coil': typeof CoilListCoilRoute
  '/coil/update-coil': typeof CoilUpdateCoilRoute
  '/order/create-orders': typeof OrderCreateOrdersRoute
  '/order/delete-order': typeof OrderDeleteOrderRoute
  '/order/list-order': typeof OrderListOrderRoute
  '/order/update-order': typeof OrderUpdateOrderRoute
  '/wire/create-wire': typeof WireCreateWireRoute
  '/wire/delete-wire': typeof WireDeleteWireRoute
  '/wire/list-wire': typeof WireListWireRoute
  '/wire/update-wire': typeof WireUpdateWireRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/coil/create-coil'
    | '/coil/delete-coil'
    | '/coil/list-coil'
    | '/coil/update-coil'
    | '/order/create-orders'
    | '/order/delete-order'
    | '/order/list-order'
    | '/order/update-order'
    | '/wire/create-wire'
    | '/wire/delete-wire'
    | '/wire/list-wire'
    | '/wire/update-wire'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/coil/create-coil'
    | '/coil/delete-coil'
    | '/coil/list-coil'
    | '/coil/update-coil'
    | '/order/create-orders'
    | '/order/delete-order'
    | '/order/list-order'
    | '/order/update-order'
    | '/wire/create-wire'
    | '/wire/delete-wire'
    | '/wire/list-wire'
    | '/wire/update-wire'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/coil/create-coil'
    | '/coil/delete-coil'
    | '/coil/list-coil'
    | '/coil/update-coil'
    | '/order/create-orders'
    | '/order/delete-order'
    | '/order/list-order'
    | '/order/update-order'
    | '/wire/create-wire'
    | '/wire/delete-wire'
    | '/wire/list-wire'
    | '/wire/update-wire'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CoilCreateCoilRoute: typeof CoilCreateCoilRoute
  CoilDeleteCoilRoute: typeof CoilDeleteCoilRoute
  CoilListCoilRoute: typeof CoilListCoilRoute
  CoilUpdateCoilRoute: typeof CoilUpdateCoilRoute
  OrderCreateOrdersRoute: typeof OrderCreateOrdersRoute
  OrderDeleteOrderRoute: typeof OrderDeleteOrderRoute
  OrderListOrderRoute: typeof OrderListOrderRoute
  OrderUpdateOrderRoute: typeof OrderUpdateOrderRoute
  WireCreateWireRoute: typeof WireCreateWireRoute
  WireDeleteWireRoute: typeof WireDeleteWireRoute
  WireListWireRoute: typeof WireListWireRoute
  WireUpdateWireRoute: typeof WireUpdateWireRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CoilCreateCoilRoute: CoilCreateCoilRoute,
  CoilDeleteCoilRoute: CoilDeleteCoilRoute,
  CoilListCoilRoute: CoilListCoilRoute,
  CoilUpdateCoilRoute: CoilUpdateCoilRoute,
  OrderCreateOrdersRoute: OrderCreateOrdersRoute,
  OrderDeleteOrderRoute: OrderDeleteOrderRoute,
  OrderListOrderRoute: OrderListOrderRoute,
  OrderUpdateOrderRoute: OrderUpdateOrderRoute,
  WireCreateWireRoute: WireCreateWireRoute,
  WireDeleteWireRoute: WireDeleteWireRoute,
  WireListWireRoute: WireListWireRoute,
  WireUpdateWireRoute: WireUpdateWireRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/coil/create-coil",
        "/coil/delete-coil",
        "/coil/list-coil",
        "/coil/update-coil",
        "/order/create-orders",
        "/order/delete-order",
        "/order/list-order",
        "/order/update-order",
        "/wire/create-wire",
        "/wire/delete-wire",
        "/wire/list-wire",
        "/wire/update-wire"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/coil/create-coil": {
      "filePath": "coil/create-coil.tsx"
    },
    "/coil/delete-coil": {
      "filePath": "coil/delete-coil.tsx"
    },
    "/coil/list-coil": {
      "filePath": "coil/list-coil.tsx"
    },
    "/coil/update-coil": {
      "filePath": "coil/update-coil.tsx"
    },
    "/order/create-orders": {
      "filePath": "order/create-orders.tsx"
    },
    "/order/delete-order": {
      "filePath": "order/delete-order.tsx"
    },
    "/order/list-order": {
      "filePath": "order/list-order.tsx"
    },
    "/order/update-order": {
      "filePath": "order/update-order.tsx"
    },
    "/wire/create-wire": {
      "filePath": "wire/create-wire.tsx"
    },
    "/wire/delete-wire": {
      "filePath": "wire/delete-wire.tsx"
    },
    "/wire/list-wire": {
      "filePath": "wire/list-wire.tsx"
    },
    "/wire/update-wire": {
      "filePath": "wire/update-wire.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
